apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-frontend
  template:
    metadata:
      labels:
        app: zabbix-frontend
    spec:
      containers:
        - name: zabbix-frontend
          image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
          env:
            - name: ZBX_SERVER_HOST
              value: zabbix-server.default.svc.cluster.local
            - name: DB_SERVER_HOST
              value: postgres.default.svc.cluster.local
            - name: POSTGRES_USER
              value: "zabbix"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "zabbix"
          ports:
            - containerPort: 8080
