apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-snmp
spec:
  storageClassName: "standard-rwo"
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pvc-snmp-zabbix-server-0 #pvc-snmp
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/[PROJECT]/regions/[REGION]/disks/[DISK]
    fsType: ext4
