apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:alpine-6.0-latest      
          env:
            - name: DB_SERVER_HOST
              value: postgres.default.svc.cluster.local
            - name: POSTGRES_USER
              value: "zabbix"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "zabbix"
            - name: ZBX_ENABLE_SNMP_TRAPS
              value: "true"
          volumeMounts:
            - mountPath: /var/lib/zabbix/snmptraps
              name: volume-snmp
          ports:
            - containerPort: 10051
        - name: zabbix-agent
          image: zabbix/zabbix-agent2:alpine-6.0-latest
          env:
            - name: ZBX_HOSTNAME
              value: "zabbix-server"
            - name: ZBX_SERVER_HOST
              value: localhost
        - name: zabbix-snmptraps
          image: zabbix/zabbix-snmptraps:alpine-6.0-latest
          ports:
            - containerPort: 1162
          volumeMounts:
            - mountPath: /var/lib/zabbix/snmptraps
              name: volume-snmp
      volumes:
        - name: volume-snmp
          persistentVolumeClaim:
            claimName: pvc-snmp