apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: pvc-snmp
spec:
  storageClassName: "standard-rwo"
  volumeName: pv-snmp
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi