apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-snmp
spec:
  storageClassName: "standard-rwo"
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pvc-snmp
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/gcpsa-sandbox/regions/asia-east1/disks/pvc-snmp
    fsType: ext4