apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zabbix-frontend
  template:
    metadata:
      labels:
        app: zabbix-frontend
    spec:
      containers:
      - name: zabbix-frontend
        image: zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
        env:
         - name: DB_SERVER_HOST
           value: "10.28.108.6"
         - name: POSTGRES_USER
           value: "zabbix"
         - name: POSTGRES_PASSWORD
           value: "zabbix"
         - name: POSTGRES_DB
           value: "zabbix"
         - name: ZBX_ENABLE_SNMP_TRAPS
           value: "true"
        ports:
        - containerPort: 8080
