apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-server
  namespace: zabbix
spec:
  serviceName: zabbix-server
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - asia-east1-b
                      - asia-east1-c
      serviceAccountName: ksa-cloudsqlproxy
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
          env:
            - name: DB_SERVER_HOST
              value: 127.0.0.1
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: zabbix-secret
                  key: database
            - name: ZBX_ENABLE_SNMP_TRAPS
              value: "true"
          ports:
            - containerPort: 10051
        - name: zabbix-agent
          image: zabbix/zabbix-agent2:alpine-6.4-latest
          env:
            - name: ZBX_HOSTNAME
              value: zabbix-server
            - name: ZBX_SERVER_HOST
              value: 127.0.0.1
        - name: zabbix-snmptraps
          image: zabbix/zabbix-snmptraps:alpine-6.4-latest
          ports:
            - containerPort: 1162
          volumeMounts:
            - mountPath: /var/lib/zabbix/snmptraps
              name: pvc-snmp
        - name: cloud-sql-proxy
          # It is recommended to use the latest version of the Cloud SQL Auth Proxy
          # Make sure to update on a regular schedule!
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.5.0 # make sure to use the latest version
          args:
            # If connecting from a VPC-native GKE cluster, you can use the
            # following flag to have the proxy connect over private IP
            - --private-ip
            # Replace DB_PORT with the port the proxy should listen on
            - --port=5432
            - gcpsa-sandbox:asia-east1:zabbix-instance
          securityContext:
            # The default Cloud SQL Auth Proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true
          # Resource configuration depends on an application's requirements. You
          # should adjust the following values based on what your application
          # needs. For details, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            requests:
              # The proxy's memory use scales linearly with the number of active
              # connections. Fewer open connections will use less memory. Adjust
              # this value based on your application's requirements.
              memory: "2Gi"
              # The proxy's CPU use scales linearly with the amount of IO between
              # the database and the application. Adjust this value based on your
              # application's requirements.
              cpu: "1"
  volumeClaimTemplates:
    - metadata:
        name: pvc-snmp
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 30Gi

