apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-server
  namespace: zabbix
spec:
  serviceName: zabbix-server
  replicas: 2
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: topology.kubernetes.io/zone
      #               operator: In
      #               values:
      #                 - asia-east1-b
      #                 - asia-east1-c
      serviceAccountName: ksa-cloudsqlproxy
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
          env:
            - name: DB_SERVER_HOST
              value: 127.0.0.1
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: zabbix-secret
                  key: database
            - name: ZBX_ENABLE_SNMP_TRAPS
              value: "true"
            # HA Mode
            - name: ZBX_AUTOHANODENAME
              value: "fqdn"
            - name: ZBX_AUTONODEADDRESS
              value: "fqdn"
            - name: ZBX_SERVICEMANAGERSYNCFREQUENCY
              value: "10"
            - name: ZBX_PROBLEMHOUSEKEEPINGFREQUENCY
              value: "60"
          ports:
            - containerPort: 10051
          resources:
            limits:
              cpu: "500m"
              ephemeral-storage: 1Gi
              memory: 1Gi
            requests:
              cpu: "500m"
              ephemeral-storage: 1Gi
              memory: 1Gi
        - name: zabbix-agent
          image: zabbix/zabbix-agent2:alpine-6.0-latest
          env:
            - name: ZBX_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Get pod name
            - name: ZBX_ACTIVESERVERS
              value: 127.0.0.1:10051
            - name: ZBX_PASSIVE_ALLOW
              value: "false"
          resources:
            limits:
              cpu: "500m"
              ephemeral-storage: 1Gi
              memory: 1Gi
            requests:
              cpu: "500m"
              ephemeral-storage: 1Gi
              memory: 1Gi
        - name: zabbix-snmptraps
          image: zabbix/zabbix-snmptraps:alpine-6.0-latest
          ports:
            - containerPort: 1162
          volumeMounts:
            - mountPath: /var/lib/zabbix/snmptraps
              name: pvc-snmp
          resources:
            limits:
              cpu: "500m"
              ephemeral-storage: 1Gi
              memory: 1Gi
            requests:
              cpu: "500m"
              ephemeral-storage: 1Gi
              memory: 1Gi
        - name: cloud-sql-proxy
          # It is recommended to use the latest version of the Cloud SQL Auth Proxy
          # Make sure to update on a regular schedule!
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.5.0 # make sure to use the latest version
          env:
            - name: INSTANCE_CONNECTION
              value: gcpsa-sandbox:asia-east1:zabbix-instance
          args:
            # If connecting from a VPC-native GKE cluster, you can use the
            # following flag to have the proxy connect over private IP
            - --private-ip
            # Replace DB_PORT with the port the proxy should listen on
            - --port=5432
            - $(INSTANCE_CONNECTION)
          securityContext:
            # The default Cloud SQL Auth Proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true
          # Resource configuration depends on an application's requirements. You
          # should adjust the following values based on what your application
          # needs. For details, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            requests:
              # The proxy's memory use scales linearly with the number of active
              # connections. Fewer open connections will use less memory. Adjust
              # this value based on your application's requirements.
              memory: "1Gi"
              # The proxy's CPU use scales linearly with the amount of IO between
              # the database and the application. Adjust this value based on your
              # application's requirements.
              cpu: "500m"
              ephemeral-storage: 1Gi
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: pvc-snmp
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 30Gi

