apiVersion: v1
kind: Service
metadata:
  name: zabbix-server-nlb
spec:
  type: LoadBalancer
  selector:
    app: zabbix-server
  ports:
  - name: expose-tcp
    protocol: TCP
    port: 10051
    targetPort: 10051
  - name: expose-udp
    protocol: UDP
    port: 162
    targetPort: 1162
