apiVersion: v1
kind: PersistentVolume
metadata:
  name: snmp-pv
spec:
  storageClassName: "standard-rwo"
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: zabbix-pvc
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/gcpsa-sandbox/regions/asia-east1/disks/gke-zabbix-disk
    fsType: FS_TYPE
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: zabbix-pvc
spec:
  storageClassName: "standard-rwo"
  volumeName: snmp-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi