apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
        env:
         - name: DB_SERVER_HOST
           value: "10.28.108.6"
         - name: POSTGRES_USER
           value: "zabbix"
         - name: POSTGRES_PASSWORD
           value: "zabbix"
         - name: POSTGRES_DB
           value: "zabbix"
         - name: ZBX_ENABLE_SNMP_TRAPS
           value: "true"
        ports:
        - containerPort: 10051
