apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-frontend
  template:
    metadata:
      labels:
        app: zabbix-frontend
    spec:
      serviceAccountName: ksa-cloudsqlproxy      
      containers:
      - name: zabbix-frontend
        image: zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
        env:
        - name: DB_SERVER_HOST
          value: 127.0.0.1
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: database
        ports:
        - containerPort: 8080
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL Auth Proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.5.0 # make sure to use the latest version
        args:
          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          - --private-ip
          # Replace DB_PORT with the port the proxy should listen on
          - --port=5432
          - <INSTANCE_CONNECTION_NAME>
        securityContext:
          # The default Cloud SQL Auth Proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        # Resource configuration depends on an application's requirements. You
        # should adjust the following values based on what your application
        # needs. For details, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          requests:
            # The proxy's memory use scales linearly with the number of active
            # connections. Fewer open connections will use less memory. Adjust
            # this value based on your application's requirements.
            memory: "2Gi"
            # The proxy's CPU use scales linearly with the amount of IO between
            # the database and the application. Adjust this value based on your
            # application's requirements.
            cpu: "1"