apiVersion: v1
kind: Service
metadata:
  name: zabbix-frontend
  namespace: zabbix
spec:
  type: NodePort
  selector:
    app: zabbix-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
